export const ADD_SECRET = 'ADD_SECRET'

export const FETCH_SECRET_REQUEST = 'FETCH_SECRET_REQUEST'

export const FETCH_SECRET_SUCCESS = 'FETCH_SECRET_SUCCESS'

export const FETCH_SECRET_FAILURE = 'FETCH_SECRET_FAILURE'
