export const ADD_SECRET = 'ADD_SECRET'
export type ADD_SECRET = typeof ADD_SECRET;

export const FETCH_SECRET = 'FETCH_SECRET'
export type FETCH_SECRET = typeof FETCH_SECRET;

export const FETCH_SECRET_SUCCESS = 'FETCH_SECRET_SUCCESS'
export type FETCH_SECRET_SUCCESS = typeof FETCH_SECRET_SUCCESS;

export const FETCH_SECRET_FAILURE = 'FETCH_SECRET_FAILURE'
export type FETCH_SECRET_FAILURE = typeof FETCH_SECRET_FAILURE;
